### ISSUE TITLE
electrumsv reset (develop branch) throws an error now

### ISSUE THREAD

**Issue by AustEcon** [electrumsv/electrumsv-sdk#140]
Here is the logging output:

```
2022-05-30 01:39:29 DEBUG    electrumsv               Deleting wallet...
2022-05-30 01:39:29 DEBUG    electrumsv               Wallet directory before: []
2022-05-30 01:39:29 DEBUG    electrumsv               Wallet directory after: []
2022-05-30 01:39:29 DEBUG    electrumsv               Creating wallet...
Wallet saved in '/home/vsts/agents/2.204.0/my_portable_sdk_datadir/component_datadirs/electrumsv/electrumsv1/regtest/wallets/worker1.sqlite'
2022-05-30 01:39:47 DEBUG    electrumsv               New wallet created at : /home/vsts/agents/2.204.0/my_portable_sdk_datadir/component_datadirs/electrumsv/electrumsv1/regtest/wallets/worker1.sqlite 
Traceback (most recent call last):
  File "/home/vsts/agents/2.204.0/my_portable_sdk_datadir/remote_repos/electrumsv/electrum-sv", line 36, in <module>
    main()
  File "/home/vsts/agents/2.204.0/my_portable_sdk_datadir/remote_repos/electrumsv/electrumsv/main.py", line 457, in main
    run_non_RPC(config)
  File "/home/vsts/agents/2.204.0/my_portable_sdk_datadir/remote_repos/electrumsv/electrumsv/main.py", line 116, in run_non_RPC
    parent_wallet = Wallet(storage, password)
  File "/home/vsts/agents/2.204.0/my_portable_sdk_datadir/remote_repos/electrumsv/electrumsv/wallet.py", line 2200, in __init__
    self.load_state()
  File "/home/vsts/agents/2.204.0/my_portable_sdk_datadir/remote_repos/electrumsv/electrumsv/wallet.py", line 2255, in load_state
    assert app_state.headers is not None
AssertionError

```

**Comment by AustEcon** [comment]
Fixed in: https://github.com/electrumsv/electrumsv/pull/897
