### ISSUE TITLE
Adjustments to get electrum on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by paradisaeidae** [electrumsv/electrumsv-sdk#142]
Ubuntu 22.04 LTS

do-release-upgrade will put python3.10 on your box.
Leave electrum-sdk in place.
Install Python3.9 as described below.

**Comment by paradisaeidae** [comment]
So there is hazard here:

Traceback (most recent call last):
  File "~/.electrumsv-sdk/remote_repos/electrumsv/electrumsv/gui/qt/wallet_wizard.py", line 626, in _event_click_open_selected_file
    self._attempt_open_wallet(wallet_path, change_page=True)
  File "~/.electrumsv-sdk/remote_repos/electrumsv/electrumsv/gui/qt/wallet_wizard.py", line 571, in _attempt_open_wallet
    password = request_password(self, storage, entry)
  File "~/.electrumsv-sdk/remote_repos/electrumsv/electrumsv/gui/qt/wallet_wizard.py", line 200, in request_password
    dialog = PasswordDialog(parent, PASSWORD_REQUEST_TEXT,
  File "~/.electrumsv-sdk/remote_repos/electrumsv/electrumsv/gui/qt/password_dialog.py", line 314, in __init__
    self.pw = pw = PasswordLineEdit()
  File "~/.electrumsv-sdk/remote_repos/electrumsv/electrumsv/gui/qt/password_dialog.py", line 92, in __init__
    self.keyboard = VirtualKeyboard(self.pw)
  File "~/.electrumsv-sdk/remote_repos/electrumsv/electrumsv/gui/qt/virtual_keyboard.py", line 61, in __init__
    self.refresh_button = vkb_button(self._refresh)
  File "~/.electrumsv-sdk/remote_repos/electrumsv/electrumsv/gui/qt/virtual_keyboard.py", line 49, in vkb_button
    button.setFixedWidth(app_state.app.dpi / 3.6)
TypeError: setFixedWidth(self, int): argument 1 has unexpected type 'float'
 
Additional information
ElectrumSV version: 1.4.0b1 
Python version: 3.10.4 (main, Apr 2 2022, 09:04:19) [GCC 11.2.0] 
Operating system: Linux-5.15.0-40-generic-x86_64-with-glibc2.35 
Wallet type: Unknown 
Locale: en_US

**Comment by rt121212121** [comment]
Do not use 1.4.0. We do not support wallet upgrades for it. The default branch of our repo is releases-1.3 for a reason.

**Comment by paradisaeidae** [comment]
I am on occasional pythonista.
So previous advice has been adjusted.

I'm one who is keen to keep linux system core recent.
https://arstechnica.com/information-technology/2022/07/intel-and-amd-cpus-vulnerable-to-a-new-speculative-execution-attack/
So practice do-system-upgrade when appropriate.
The recent action reduced my (system) install of python3.9.
Replaced with 3.10.
So a manual re-install of 3.9 is required for elsdk for current release.
https://techviewleo.com/how-to-install-python-on-ubuntu-linux/
Recommend ./configure --prefix=$HOME/python3.9
In a script I suggest somethings:
export PYTHONPATH=$HOME/.electrumsv-sdk/python_libs/electrumsv  << in bash.rc or appropriate >>
alias elsdk='$HOME/python3.9/bin/electrumsv-sdk'
alias python3='$HOME/python3.9/bin/python3.9'
alias python='$HOME/python3.9/bin/python3.9'
alias pip3='$HOME/python3.9/bin/pip3'
alias pip='$HOME/python3.9/bin/pip3'

First line of $HOME/python3.9/bin/electrumsv-sdk:
#!/usr/bin/env python3.9

To have an Xterm server running on Win10, suggest MobaXterm
Once started possible to gui from other terminal with:
export DISPLAY=localhost:10.0  << adjust as observed >>
